name: Rebase main into gh-pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to manually trigger this workflow

jobs:
  rebase-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check out gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      - name: Rebase main onto gh-pages
        run: |
          git rebase main

      - name: Push rebased changes to gh-pages
        run: |
          git push origin gh-pages --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
